properties {
  key: "first-file"
  value: "/tmp/first-file.txt"
}
properties {
  key: "first-path"
  value: "/tmp/first-path.txt"
}
properties {
  key: "second-file"
  value: "/tmp/second-file.txt"
}
properties {
  key: "second-path"
  value: "/tmp/second-path.txt"
}
properties {
  key: "third-file"
  value: "/tmp/third-file.txt"
}
properties {
  key: "third-path"
  value: "/tmp/third-path.txt"
}
components {
  name: "second-configurable"
  type: "com.oracle.labs.mlrg.olcut.config.StringConfigurable"
  properties {
    key: "one"
    value: "alpha"
  }
  properties {
    key: "three"
    value: "gamma"
  }
  properties {
    key: "two"
    value: "beta"
  }
}
components {
  name: "first-configurable"
  type: "com.oracle.labs.mlrg.olcut.config.StringConfigurable"
  properties {
    key: "one"
    value: "A"
  }
  properties {
    key: "three"
    value: "C"
  }
  properties {
    key: "two"
    value: "B"
  }
}
components {
  name: "all-config"
  type: "com.oracle.labs.mlrg.olcut.config.AllFieldsConfigurable"
  properties {
    key: "BoolField"
    value: "true"
  }
  properties {
    key: "ByteField"
    value: "123"
  }
  properties {
    key: "DoubleField"
    value: "3.141592653589793"
  }
  properties {
    key: "FloatField"
    value: "3.14159"
  }
  properties {
    key: "LongField"
    value: "123456789"
  }
  properties {
    key: "ShortField"
    value: "1234"
  }
  properties {
    key: "atomicIntegerField"
    value: "1"
  }
  properties {
    key: "atomicLongField"
    value: "123456789"
  }
  properties {
    key: "boolField"
    value: "true"
  }
  properties {
    key: "byteField"
    value: "123"
  }
  properties {
    key: "charField"
    value: "a"
  }
  properties {
    key: "characterField"
    value: "a"
  }
  properties {
    key: "configurableField"
    value: "first-configurable"
  }
  properties {
    key: "configurableSubclassField"
    value: "second-configurable"
  }
  properties {
    key: "dateField"
    value: "1948-06-21"
  }
  properties {
    key: "dateTimeField"
    value: "1949-06-16T20:30:00+01:00"
  }
  properties {
    key: "doubleField"
    value: "3.141592653589793"
  }
  properties {
    key: "enumField"
    value: "F"
  }
  properties {
    key: "fileField"
    value: "/tmp/a-file.txt"
  }
  properties {
    key: "floatField"
    value: "3.14159"
  }
  properties {
    key: "intField"
    value: "12345"
  }
  properties {
    key: "integerField"
    value: "12345"
  }
  properties {
    key: "longField"
    value: "123456789"
  }
  properties {
    key: "pathField"
    value: "/tmp/a-path.txt"
  }
  properties {
    key: "shortField"
    value: "1234"
  }
  properties {
    key: "stringField"
    value: "monkeys"
  }
  properties {
    key: "timeField"
    value: "12:34+00:00"
  }
  properties {
    key: "urlField"
    value: "file:///tmp/a-file-url.txt"
  }
  list_property {
    name: "listStringField"
    item: "e"
    item: "pi"
  }
  list_property {
    name: "setDoubleField"
    item: "2.71828"
    item: "3.14159"
  }
  list_property {
    name: "setConfigurableSubclassField"
    item: "first-configurable"
    item: "second-configurable"
  }
  list_property {
    name: "doubleArrayField"
    item: "1e-16"
    item: "2e-16"
    item: "3.16"
  }
  list_property {
    name: "intArrayField"
    item: "123456"
    item: "23456"
    item: "3456"
  }
  list_property {
    name: "configurableArrayField"
    item: "first-configurable"
    item: "second-configurable"
  }
  list_property {
    name: "configurableSubclassArrayField"
    item: "first-configurable"
    item: "second-configurable"
  }
  list_property {
    name: "enumSetField"
    item: "A"
    item: "C"
    item: "E"
  }
  list_property {
    name: "setPathField"
    item: "/foo/bar/first-path"
    item: "/foo/bar/second-path"
  }
  list_property {
    name: "listDoubleField"
    item: "2.71828"
    item: "3.14159"
  }
  list_property {
    name: "charArrayField"
    item: "1"
    item: "2"
    item: "3"
  }
  list_property {
    name: "longArrayField"
    item: "9223372036854775807"
    item: "9223372036854775806"
    item: "5"
  }
  list_property {
    name: "listConfigurableSubclassField"
    item: "first-configurable"
    item: "second-configurable"
  }
  list_property {
    name: "shortArrayField"
    item: "12345"
    item: "2345"
    item: "345"
  }
  list_property {
    name: "stringArrayField"
    item: "gibbons"
    item: "baboons"
    item: "gorillas"
  }
  list_property {
    name: "setStringField"
    item: "e"
    item: "pi"
  }
  list_property {
    name: "floatArrayField"
    item: "1.1f"
    item: "2.3"
    item: "3.5"
  }
  list_property {
    name: "byteArrayField"
    item: "123"
    item: "23"
    item: "3"
  }
  map_property {
    name: "mapStringField"
    elements {
      key: "first"
      value: "A"
    }
    elements {
      key: "second"
      value: "B"
    }
  }
  map_property {
    name: "mapConfigurableSubclassField"
    elements {
      key: "first"
      value: "first-configurable"
    }
    elements {
      key: "second"
      value: "second-configurable"
    }
    elements {
      key: "third"
      value: "third-configurable"
    }
  }
  map_property {
    name: "mapDoubleField"
    elements {
      key: "e"
      value: "2.71828"
    }
    elements {
      key: "pi"
      value: "3.14159"
    }
  }
  map_property {
    name: "mapFileField"
    elements {
      key: "first"
      value: "/foo/bar/first-file"
    }
    elements {
      key: "second"
      value: "/foo/bar/second-file"
    }
    elements {
      key: "third"
      value: "/foo/bar/third-file"
    }
  }
}
components {
  name: "third-configurable"
  type: "com.oracle.labs.mlrg.olcut.config.StringConfigurable"
  properties {
    key: "one"
    value: "uno"
  }
  properties {
    key: "three"
    value: "tres"
  }
  properties {
    key: "two"
    value: "dos"
  }
}

