component {
  name: "a"
  type: "com.oracle.labs.mlrg.olcut.config.test.ArrayConfigurable"
  list_property {
    name: "floatArray"
    item: "1.1f"
    item: "2.3"
    item: "3.5"
  }
  list_property {
    name: "floatArray"
    item: "1.1f"
    item: "2.3"
    item: "3.5"
  }
  list_property {
    name: "doubleArray"
    item: "1e-16"
    item: "2e-16"
    item: "3.16"
  }
  list_property {
    name: "longArray"
    item: "9223372036854775807"
    item : "9223372036854775806"
    item : "5"
  }
  list_property {
    name: "intArray"
    item: "1"
    item: "2"
    item: "3"
  }
}