component {
  name: "a"
  type: "com.oracle.labs.mlrg.olcut.config.test.FooMapConfigurable"
  map_property {
    name: "map"
    elements {
      key: "first"
      value: "foo1"
    }
    elements {
      key: "second"
      value: "foo2"
    }
  }
  map_property {
    name: "map"
    elements {
      key: "first"
      value: "foo1"
    }
    elements {
      key: "second"
      value: "foo2"
    }
  }
}
component {
  name: "foo1"
  type: "com.oracle.labs.mlrg.olcut.config.test.FooConfigurable"
  properties {
    key: "name"
    value: "foo1"
  }
  properties {
    key: "value"
    value: "1"
  }
}
component {
  name: "foo2"
  type: "com.oracle.labs.mlrg.olcut.config.test.FooConfigurable"
  properties {
    key: "name"
    value: "foo2"
  }
  properties {
    key: "value"
    value: "2"
  }
}