components {
  name: "nastyStringTest"
  type: "com.oracle.labs.mlrg.olcut.config.StringConfigurable"
  properties {
    key: "one"
    value: "([^a-z0-9_!#$%&*@\357\274\240]|^|RT:?)(@\357\274\240+)([a-z0-9_]{1,20})(/[a-z][a-z0-9_\\\\-]{0,24})?"
  }
  properties {
    key: "three"
    value: "&&"
  }
  properties {
    key: "two"
    value: "@\357\274\240"
  }
}

