properties {
  key: "a"
  value: "alpha"
}
properties {
  key: "b"
  value: "beta"
}
properties {
  key: "c"
  value: "charlie"
}
properties {
  key: "stringA"
  value: "HK-47"
}
config_file {
  name: "partB"
  value: "propertyChainingConfigB.xml"
}
components {
  name: "configA"
  type: "com.oracle.labs.mlrg.olcut.config.StringConfigurable"
  properties {
    key: "one"
    value: "fileA"
  }
  properties {
    key: "three"
    value: "${c}"
  }
  properties {
    key: "two"
    value: "${b}"
  }
}

