components {
  name: "type-b"
  type: "com.oracle.labs.mlrg.olcut.config.test.BasicConfigurable"
  properties {
    key: "d"
    value: "6.3"
  }
  properties {
    key: "i"
    value: "3"
  }
  properties {
    key: "s"
    value: "two"
  }
}
components {
  name: "type-a"
  type: "com.oracle.labs.mlrg.olcut.config.test.BasicConfigurable"
  properties {
    key: "d"
    value: "3.0"
  }
  properties {
    key: "i"
    value: "2"
  }
  properties {
    key: "s"
    value: "one"
  }
}
components {
  name: "type-list"
  type: "com.oracle.labs.mlrg.olcut.config.test.ListTypeConfigurable"
  list_property {
    name: "list"
    item: "default"
    item: "type-a"
    item: "type-b"
  }
}
components {
  name: "default"
  type: "com.oracle.labs.mlrg.olcut.config.test.BasicConfigurable"
}