components {
  name: "simple"
  type: "com.oracle.labs.mlrg.olcut.config.SimpleConfigurable"
  properties {
    key: "simpel"
    value: "10"
  }
}
components {
  name: "simple2"
  type: "com.oracle.labs.mlrg.olcut.config.SimpleConfigurable"
  properties {
    key: "simpel"
    value: "5"
  }
  properties {
    key: "simple"
    value: "10"
  }
}

