// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

// Protobuf Java Version: 3.25.5
package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

/**
 * <pre>
 *
 *A configurable component.
 * </pre>
 *
 * Protobuf type {@code olcut.ComponentProto}
 */
public final class ComponentProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:olcut.ComponentProto)
    ComponentProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ComponentProto.newBuilder() to construct.
  private ComponentProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ComponentProto() {
    name_ = "";
    type_ = "";
    listProperty_ = java.util.Collections.emptyList();
    mapProperty_ = java.util.Collections.emptyList();
    override_ = "";
    serialized_ = "";
    entries_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ComponentProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>optional string type = 2;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 2;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROPERTIES_FIELD_NUMBER = 3;
  private static final class PropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_PropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> properties_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetProperties() {
    if (properties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PropertiesDefaultEntryHolder.defaultEntry);
    }
    return properties_;
  }
  public int getPropertiesCount() {
    return internalGetProperties().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override
  public boolean containsProperties(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getProperties() {
    return getPropertiesMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
    return internalGetProperties().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; properties = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LIST_PROPERTY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto> listProperty_;
  /**
   * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto> getListPropertyList() {
    return listProperty_;
  }
  /**
   * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder> 
      getListPropertyOrBuilderList() {
    return listProperty_;
  }
  /**
   * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
   */
  @java.lang.Override
  public int getListPropertyCount() {
    return listProperty_.size();
  }
  /**
   * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto getListProperty(int index) {
    return listProperty_.get(index);
  }
  /**
   * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder getListPropertyOrBuilder(
      int index) {
    return listProperty_.get(index);
  }

  public static final int MAP_PROPERTY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto> mapProperty_;
  /**
   * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto> getMapPropertyList() {
    return mapProperty_;
  }
  /**
   * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder> 
      getMapPropertyOrBuilderList() {
    return mapProperty_;
  }
  /**
   * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
   */
  @java.lang.Override
  public int getMapPropertyCount() {
    return mapProperty_.size();
  }
  /**
   * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto getMapProperty(int index) {
    return mapProperty_.get(index);
  }
  /**
   * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder getMapPropertyOrBuilder(
      int index) {
    return mapProperty_.get(index);
  }

  public static final int OVERRIDE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object override_ = "";
  /**
   * <code>optional string override = 6;</code>
   * @return Whether the override field is set.
   */
  @java.lang.Override
  public boolean hasOverride() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string override = 6;</code>
   * @return The override.
   */
  @java.lang.Override
  public java.lang.String getOverride() {
    java.lang.Object ref = override_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      override_ = s;
      return s;
    }
  }
  /**
   * <code>optional string override = 6;</code>
   * @return The bytes for override.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOverrideBytes() {
    java.lang.Object ref = override_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      override_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPORTABLE_FIELD_NUMBER = 7;
  private boolean exportable_ = false;
  /**
   * <code>optional bool exportable = 7;</code>
   * @return Whether the exportable field is set.
   */
  @java.lang.Override
  public boolean hasExportable() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool exportable = 7;</code>
   * @return The exportable.
   */
  @java.lang.Override
  public boolean getExportable() {
    return exportable_;
  }

  public static final int IMPORTABLE_FIELD_NUMBER = 8;
  private boolean importable_ = false;
  /**
   * <code>optional bool importable = 8;</code>
   * @return Whether the importable field is set.
   */
  @java.lang.Override
  public boolean hasImportable() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bool importable = 8;</code>
   * @return The importable.
   */
  @java.lang.Override
  public boolean getImportable() {
    return importable_;
  }

  public static final int LEASETIME_FIELD_NUMBER = 9;
  private long leaseTime_ = 0L;
  /**
   * <code>optional int64 leaseTime = 9;</code>
   * @return Whether the leaseTime field is set.
   */
  @java.lang.Override
  public boolean hasLeaseTime() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 leaseTime = 9;</code>
   * @return The leaseTime.
   */
  @java.lang.Override
  public long getLeaseTime() {
    return leaseTime_;
  }

  public static final int SERIALIZED_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serialized_ = "";
  /**
   * <code>optional string serialized = 10;</code>
   * @return Whether the serialized field is set.
   */
  @java.lang.Override
  public boolean hasSerialized() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string serialized = 10;</code>
   * @return The serialized.
   */
  @java.lang.Override
  public java.lang.String getSerialized() {
    java.lang.Object ref = serialized_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serialized_ = s;
      return s;
    }
  }
  /**
   * <code>optional string serialized = 10;</code>
   * @return The bytes for serialized.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSerializedBytes() {
    java.lang.Object ref = serialized_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serialized_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRIES_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entries_ = "";
  /**
   * <code>optional string entries = 11;</code>
   * @return Whether the entries field is set.
   */
  @java.lang.Override
  public boolean hasEntries() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string entries = 11;</code>
   * @return The entries.
   */
  @java.lang.Override
  public java.lang.String getEntries() {
    java.lang.Object ref = entries_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entries_ = s;
      return s;
    }
  }
  /**
   * <code>optional string entries = 11;</code>
   * @return The bytes for entries.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntriesBytes() {
    java.lang.Object ref = entries_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entries_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProperties(),
        PropertiesDefaultEntryHolder.defaultEntry,
        3);
    for (int i = 0; i < listProperty_.size(); i++) {
      output.writeMessage(4, listProperty_.get(i));
    }
    for (int i = 0; i < mapProperty_.size(); i++) {
      output.writeMessage(5, mapProperty_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, override_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(7, exportable_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(8, importable_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(9, leaseTime_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, serialized_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, entries_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties__);
    }
    for (int i = 0; i < listProperty_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, listProperty_.get(i));
    }
    for (int i = 0; i < mapProperty_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, mapProperty_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, override_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, exportable_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, importable_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, leaseTime_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, serialized_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, entries_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto)) {
      return super.equals(obj);
    }
    com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto other = (com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (!internalGetProperties().equals(
        other.internalGetProperties())) return false;
    if (!getListPropertyList()
        .equals(other.getListPropertyList())) return false;
    if (!getMapPropertyList()
        .equals(other.getMapPropertyList())) return false;
    if (hasOverride() != other.hasOverride()) return false;
    if (hasOverride()) {
      if (!getOverride()
          .equals(other.getOverride())) return false;
    }
    if (hasExportable() != other.hasExportable()) return false;
    if (hasExportable()) {
      if (getExportable()
          != other.getExportable()) return false;
    }
    if (hasImportable() != other.hasImportable()) return false;
    if (hasImportable()) {
      if (getImportable()
          != other.getImportable()) return false;
    }
    if (hasLeaseTime() != other.hasLeaseTime()) return false;
    if (hasLeaseTime()) {
      if (getLeaseTime()
          != other.getLeaseTime()) return false;
    }
    if (hasSerialized() != other.hasSerialized()) return false;
    if (hasSerialized()) {
      if (!getSerialized()
          .equals(other.getSerialized())) return false;
    }
    if (hasEntries() != other.hasEntries()) return false;
    if (hasEntries()) {
      if (!getEntries()
          .equals(other.getEntries())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    if (!internalGetProperties().getMap().isEmpty()) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProperties().hashCode();
    }
    if (getListPropertyCount() > 0) {
      hash = (37 * hash) + LIST_PROPERTY_FIELD_NUMBER;
      hash = (53 * hash) + getListPropertyList().hashCode();
    }
    if (getMapPropertyCount() > 0) {
      hash = (37 * hash) + MAP_PROPERTY_FIELD_NUMBER;
      hash = (53 * hash) + getMapPropertyList().hashCode();
    }
    if (hasOverride()) {
      hash = (37 * hash) + OVERRIDE_FIELD_NUMBER;
      hash = (53 * hash) + getOverride().hashCode();
    }
    if (hasExportable()) {
      hash = (37 * hash) + EXPORTABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExportable());
    }
    if (hasImportable()) {
      hash = (37 * hash) + IMPORTABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getImportable());
    }
    if (hasLeaseTime()) {
      hash = (37 * hash) + LEASETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeaseTime());
    }
    if (hasSerialized()) {
      hash = (37 * hash) + SERIALIZED_FIELD_NUMBER;
      hash = (53 * hash) + getSerialized().hashCode();
    }
    if (hasEntries()) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntries().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *A configurable component.
   * </pre>
   *
   * Protobuf type {@code olcut.ComponentProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:olcut.ComponentProto)
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder.class);
    }

    // Construct using com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      type_ = "";
      internalGetMutableProperties().clear();
      if (listPropertyBuilder_ == null) {
        listProperty_ = java.util.Collections.emptyList();
      } else {
        listProperty_ = null;
        listPropertyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (mapPropertyBuilder_ == null) {
        mapProperty_ = java.util.Collections.emptyList();
      } else {
        mapProperty_ = null;
        mapPropertyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      override_ = "";
      exportable_ = false;
      importable_ = false;
      leaseTime_ = 0L;
      serialized_ = "";
      entries_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ComponentProto_descriptor;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getDefaultInstanceForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto build() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto buildPartial() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto result = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto result) {
      if (listPropertyBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          listProperty_ = java.util.Collections.unmodifiableList(listProperty_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.listProperty_ = listProperty_;
      } else {
        result.listProperty_ = listPropertyBuilder_.build();
      }
      if (mapPropertyBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          mapProperty_ = java.util.Collections.unmodifiableList(mapProperty_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.mapProperty_ = mapProperty_;
      } else {
        result.mapProperty_ = mapPropertyBuilder_.build();
      }
    }

    private void buildPartial0(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.override_ = override_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.exportable_ = exportable_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.importable_ = importable_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.leaseTime_ = leaseTime_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.serialized_ = serialized_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.entries_ = entries_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto) {
        return mergeFrom((com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto other) {
      if (other == com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasType()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      internalGetMutableProperties().mergeFrom(
          other.internalGetProperties());
      bitField0_ |= 0x00000004;
      if (listPropertyBuilder_ == null) {
        if (!other.listProperty_.isEmpty()) {
          if (listProperty_.isEmpty()) {
            listProperty_ = other.listProperty_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureListPropertyIsMutable();
            listProperty_.addAll(other.listProperty_);
          }
          onChanged();
        }
      } else {
        if (!other.listProperty_.isEmpty()) {
          if (listPropertyBuilder_.isEmpty()) {
            listPropertyBuilder_.dispose();
            listPropertyBuilder_ = null;
            listProperty_ = other.listProperty_;
            bitField0_ = (bitField0_ & ~0x00000008);
            listPropertyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListPropertyFieldBuilder() : null;
          } else {
            listPropertyBuilder_.addAllMessages(other.listProperty_);
          }
        }
      }
      if (mapPropertyBuilder_ == null) {
        if (!other.mapProperty_.isEmpty()) {
          if (mapProperty_.isEmpty()) {
            mapProperty_ = other.mapProperty_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureMapPropertyIsMutable();
            mapProperty_.addAll(other.mapProperty_);
          }
          onChanged();
        }
      } else {
        if (!other.mapProperty_.isEmpty()) {
          if (mapPropertyBuilder_.isEmpty()) {
            mapPropertyBuilder_.dispose();
            mapPropertyBuilder_ = null;
            mapProperty_ = other.mapProperty_;
            bitField0_ = (bitField0_ & ~0x00000010);
            mapPropertyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMapPropertyFieldBuilder() : null;
          } else {
            mapPropertyBuilder_.addAllMessages(other.mapProperty_);
          }
        }
      }
      if (other.hasOverride()) {
        override_ = other.override_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasExportable()) {
        setExportable(other.getExportable());
      }
      if (other.hasImportable()) {
        setImportable(other.getImportable());
      }
      if (other.hasLeaseTime()) {
        setLeaseTime(other.getLeaseTime());
      }
      if (other.hasSerialized()) {
        serialized_ = other.serialized_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.hasEntries()) {
        entries_ = other.entries_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties__ = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableProperties().getMutableMap().put(
                  properties__.getKey(), properties__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto m =
                  input.readMessage(
                      com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.parser(),
                      extensionRegistry);
              if (listPropertyBuilder_ == null) {
                ensureListPropertyIsMutable();
                listProperty_.add(m);
              } else {
                listPropertyBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto m =
                  input.readMessage(
                      com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.parser(),
                      extensionRegistry);
              if (mapPropertyBuilder_ == null) {
                ensureMapPropertyIsMutable();
                mapProperty_.add(m);
              } else {
                mapPropertyBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              override_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              exportable_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              importable_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              leaseTime_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              serialized_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              entries_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 2;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableProperties() {
      if (properties_ == null) {
        properties_ = com.google.protobuf.MapField.newMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!properties_.isMutable()) {
        properties_ = properties_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return properties_;
    }
    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override
    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearProperties() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    public Builder removeProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableProperties() {
      bitField0_ |= 0x00000004;
      return internalGetMutableProperties().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    public Builder putProperties(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableProperties().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    public Builder putAllProperties(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableProperties().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto> listProperty_ =
      java.util.Collections.emptyList();
    private void ensureListPropertyIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        listProperty_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto>(listProperty_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder> listPropertyBuilder_;

    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto> getListPropertyList() {
      if (listPropertyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listProperty_);
      } else {
        return listPropertyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public int getListPropertyCount() {
      if (listPropertyBuilder_ == null) {
        return listProperty_.size();
      } else {
        return listPropertyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto getListProperty(int index) {
      if (listPropertyBuilder_ == null) {
        return listProperty_.get(index);
      } else {
        return listPropertyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder setListProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto value) {
      if (listPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPropertyIsMutable();
        listProperty_.set(index, value);
        onChanged();
      } else {
        listPropertyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder setListProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder builderForValue) {
      if (listPropertyBuilder_ == null) {
        ensureListPropertyIsMutable();
        listProperty_.set(index, builderForValue.build());
        onChanged();
      } else {
        listPropertyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder addListProperty(com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto value) {
      if (listPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPropertyIsMutable();
        listProperty_.add(value);
        onChanged();
      } else {
        listPropertyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder addListProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto value) {
      if (listPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListPropertyIsMutable();
        listProperty_.add(index, value);
        onChanged();
      } else {
        listPropertyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder addListProperty(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder builderForValue) {
      if (listPropertyBuilder_ == null) {
        ensureListPropertyIsMutable();
        listProperty_.add(builderForValue.build());
        onChanged();
      } else {
        listPropertyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder addListProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder builderForValue) {
      if (listPropertyBuilder_ == null) {
        ensureListPropertyIsMutable();
        listProperty_.add(index, builderForValue.build());
        onChanged();
      } else {
        listPropertyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder addAllListProperty(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto> values) {
      if (listPropertyBuilder_ == null) {
        ensureListPropertyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listProperty_);
        onChanged();
      } else {
        listPropertyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder clearListProperty() {
      if (listPropertyBuilder_ == null) {
        listProperty_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        listPropertyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public Builder removeListProperty(int index) {
      if (listPropertyBuilder_ == null) {
        ensureListPropertyIsMutable();
        listProperty_.remove(index);
        onChanged();
      } else {
        listPropertyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder getListPropertyBuilder(
        int index) {
      return getListPropertyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder getListPropertyOrBuilder(
        int index) {
      if (listPropertyBuilder_ == null) {
        return listProperty_.get(index);  } else {
        return listPropertyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder> 
         getListPropertyOrBuilderList() {
      if (listPropertyBuilder_ != null) {
        return listPropertyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listProperty_);
      }
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder addListPropertyBuilder() {
      return getListPropertyFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder addListPropertyBuilder(
        int index) {
      return getListPropertyFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.PropertyListProto list_property = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder> 
         getListPropertyBuilderList() {
      return getListPropertyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder> 
        getListPropertyFieldBuilder() {
      if (listPropertyBuilder_ == null) {
        listPropertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyListProtoOrBuilder>(
                listProperty_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        listProperty_ = null;
      }
      return listPropertyBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto> mapProperty_ =
      java.util.Collections.emptyList();
    private void ensureMapPropertyIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        mapProperty_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto>(mapProperty_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder> mapPropertyBuilder_;

    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto> getMapPropertyList() {
      if (mapPropertyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mapProperty_);
      } else {
        return mapPropertyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public int getMapPropertyCount() {
      if (mapPropertyBuilder_ == null) {
        return mapProperty_.size();
      } else {
        return mapPropertyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto getMapProperty(int index) {
      if (mapPropertyBuilder_ == null) {
        return mapProperty_.get(index);
      } else {
        return mapPropertyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder setMapProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto value) {
      if (mapPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapPropertyIsMutable();
        mapProperty_.set(index, value);
        onChanged();
      } else {
        mapPropertyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder setMapProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder builderForValue) {
      if (mapPropertyBuilder_ == null) {
        ensureMapPropertyIsMutable();
        mapProperty_.set(index, builderForValue.build());
        onChanged();
      } else {
        mapPropertyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder addMapProperty(com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto value) {
      if (mapPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapPropertyIsMutable();
        mapProperty_.add(value);
        onChanged();
      } else {
        mapPropertyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder addMapProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto value) {
      if (mapPropertyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapPropertyIsMutable();
        mapProperty_.add(index, value);
        onChanged();
      } else {
        mapPropertyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder addMapProperty(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder builderForValue) {
      if (mapPropertyBuilder_ == null) {
        ensureMapPropertyIsMutable();
        mapProperty_.add(builderForValue.build());
        onChanged();
      } else {
        mapPropertyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder addMapProperty(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder builderForValue) {
      if (mapPropertyBuilder_ == null) {
        ensureMapPropertyIsMutable();
        mapProperty_.add(index, builderForValue.build());
        onChanged();
      } else {
        mapPropertyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder addAllMapProperty(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto> values) {
      if (mapPropertyBuilder_ == null) {
        ensureMapPropertyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mapProperty_);
        onChanged();
      } else {
        mapPropertyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder clearMapProperty() {
      if (mapPropertyBuilder_ == null) {
        mapProperty_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        mapPropertyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public Builder removeMapProperty(int index) {
      if (mapPropertyBuilder_ == null) {
        ensureMapPropertyIsMutable();
        mapProperty_.remove(index);
        onChanged();
      } else {
        mapPropertyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder getMapPropertyBuilder(
        int index) {
      return getMapPropertyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder getMapPropertyOrBuilder(
        int index) {
      if (mapPropertyBuilder_ == null) {
        return mapProperty_.get(index);  } else {
        return mapPropertyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder> 
         getMapPropertyOrBuilderList() {
      if (mapPropertyBuilder_ != null) {
        return mapPropertyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mapProperty_);
      }
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder addMapPropertyBuilder() {
      return getMapPropertyFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder addMapPropertyBuilder(
        int index) {
      return getMapPropertyFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.PropertyMapProto map_property = 5;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder> 
         getMapPropertyBuilderList() {
      return getMapPropertyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder> 
        getMapPropertyFieldBuilder() {
      if (mapPropertyBuilder_ == null) {
        mapPropertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.PropertyMapProtoOrBuilder>(
                mapProperty_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        mapProperty_ = null;
      }
      return mapPropertyBuilder_;
    }

    private java.lang.Object override_ = "";
    /**
     * <code>optional string override = 6;</code>
     * @return Whether the override field is set.
     */
    public boolean hasOverride() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string override = 6;</code>
     * @return The override.
     */
    public java.lang.String getOverride() {
      java.lang.Object ref = override_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        override_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string override = 6;</code>
     * @return The bytes for override.
     */
    public com.google.protobuf.ByteString
        getOverrideBytes() {
      java.lang.Object ref = override_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        override_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string override = 6;</code>
     * @param value The override to set.
     * @return This builder for chaining.
     */
    public Builder setOverride(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      override_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string override = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOverride() {
      override_ = getDefaultInstance().getOverride();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string override = 6;</code>
     * @param value The bytes for override to set.
     * @return This builder for chaining.
     */
    public Builder setOverrideBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      override_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean exportable_ ;
    /**
     * <code>optional bool exportable = 7;</code>
     * @return Whether the exportable field is set.
     */
    @java.lang.Override
    public boolean hasExportable() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool exportable = 7;</code>
     * @return The exportable.
     */
    @java.lang.Override
    public boolean getExportable() {
      return exportable_;
    }
    /**
     * <code>optional bool exportable = 7;</code>
     * @param value The exportable to set.
     * @return This builder for chaining.
     */
    public Builder setExportable(boolean value) {

      exportable_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool exportable = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExportable() {
      bitField0_ = (bitField0_ & ~0x00000040);
      exportable_ = false;
      onChanged();
      return this;
    }

    private boolean importable_ ;
    /**
     * <code>optional bool importable = 8;</code>
     * @return Whether the importable field is set.
     */
    @java.lang.Override
    public boolean hasImportable() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional bool importable = 8;</code>
     * @return The importable.
     */
    @java.lang.Override
    public boolean getImportable() {
      return importable_;
    }
    /**
     * <code>optional bool importable = 8;</code>
     * @param value The importable to set.
     * @return This builder for chaining.
     */
    public Builder setImportable(boolean value) {

      importable_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool importable = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportable() {
      bitField0_ = (bitField0_ & ~0x00000080);
      importable_ = false;
      onChanged();
      return this;
    }

    private long leaseTime_ ;
    /**
     * <code>optional int64 leaseTime = 9;</code>
     * @return Whether the leaseTime field is set.
     */
    @java.lang.Override
    public boolean hasLeaseTime() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int64 leaseTime = 9;</code>
     * @return The leaseTime.
     */
    @java.lang.Override
    public long getLeaseTime() {
      return leaseTime_;
    }
    /**
     * <code>optional int64 leaseTime = 9;</code>
     * @param value The leaseTime to set.
     * @return This builder for chaining.
     */
    public Builder setLeaseTime(long value) {

      leaseTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 leaseTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaseTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      leaseTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object serialized_ = "";
    /**
     * <code>optional string serialized = 10;</code>
     * @return Whether the serialized field is set.
     */
    public boolean hasSerialized() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string serialized = 10;</code>
     * @return The serialized.
     */
    public java.lang.String getSerialized() {
      java.lang.Object ref = serialized_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serialized_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string serialized = 10;</code>
     * @return The bytes for serialized.
     */
    public com.google.protobuf.ByteString
        getSerializedBytes() {
      java.lang.Object ref = serialized_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialized_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string serialized = 10;</code>
     * @param value The serialized to set.
     * @return This builder for chaining.
     */
    public Builder setSerialized(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serialized_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional string serialized = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialized() {
      serialized_ = getDefaultInstance().getSerialized();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>optional string serialized = 10;</code>
     * @param value The bytes for serialized to set.
     * @return This builder for chaining.
     */
    public Builder setSerializedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serialized_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object entries_ = "";
    /**
     * <code>optional string entries = 11;</code>
     * @return Whether the entries field is set.
     */
    public boolean hasEntries() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string entries = 11;</code>
     * @return The entries.
     */
    public java.lang.String getEntries() {
      java.lang.Object ref = entries_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entries_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entries = 11;</code>
     * @return The bytes for entries.
     */
    public com.google.protobuf.ByteString
        getEntriesBytes() {
      java.lang.Object ref = entries_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entries_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entries = 11;</code>
     * @param value The entries to set.
     * @return This builder for chaining.
     */
    public Builder setEntries(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entries_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entries = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntries() {
      entries_ = getDefaultInstance().getEntries();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>optional string entries = 11;</code>
     * @param value The bytes for entries to set.
     * @return This builder for chaining.
     */
    public Builder setEntriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entries_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:olcut.ComponentProto)
  }

  // @@protoc_insertion_point(class_scope:olcut.ComponentProto)
  private static final com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto();
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ComponentProto>
      PARSER = new com.google.protobuf.AbstractParser<ComponentProto>() {
    @java.lang.Override
    public ComponentProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ComponentProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ComponentProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

