// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

// Protobuf Java Version: 3.25.5
package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

public interface ConfigProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:olcut.ConfigProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  /* nullable */
java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  java.lang.String getPropertiesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> 
      getComponentsList();
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getComponents(int index);
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  int getComponentsCount();
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder> 
      getComponentsOrBuilderList();
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder getComponentsOrBuilder(
      int index);

  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> 
      getConfigFileList();
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto getConfigFile(int index);
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  int getConfigFileCount();
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder> 
      getConfigFileOrBuilderList();
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder getConfigFileOrBuilder(
      int index);

  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> 
      getSerializedObjectList();
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto getSerializedObject(int index);
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  int getSerializedObjectCount();
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder> 
      getSerializedObjectOrBuilderList();
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder getSerializedObjectOrBuilder(
      int index);
}
