// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

// Protobuf Java Version: 3.25.5
package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

/**
 * <pre>
 *
 *Root message which contains the full configuration.
 * </pre>
 *
 * Protobuf type {@code olcut.ConfigProto}
 */
public final class ConfigProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:olcut.ConfigProto)
    ConfigProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfigProto.newBuilder() to construct.
  private ConfigProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfigProto() {
    components_ = java.util.Collections.emptyList();
    configFile_ = java.util.Collections.emptyList();
    serializedObject_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConfigProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.Builder.class);
  }

  public static final int PROPERTIES_FIELD_NUMBER = 1;
  private static final class PropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_PropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> properties_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetProperties() {
    if (properties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PropertiesDefaultEntryHolder.defaultEntry);
    }
    return properties_;
  }
  public int getPropertiesCount() {
    return internalGetProperties().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  @java.lang.Override
  public boolean containsProperties(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getProperties() {
    return getPropertiesMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
    return internalGetProperties().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; properties = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int COMPONENTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> components_;
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> getComponentsList() {
    return components_;
  }
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder> 
      getComponentsOrBuilderList() {
    return components_;
  }
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  @java.lang.Override
  public int getComponentsCount() {
    return components_.size();
  }
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getComponents(int index) {
    return components_.get(index);
  }
  /**
   * <code>repeated .olcut.ComponentProto components = 2;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder getComponentsOrBuilder(
      int index) {
    return components_.get(index);
  }

  public static final int CONFIG_FILE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> configFile_;
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> getConfigFileList() {
    return configFile_;
  }
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder> 
      getConfigFileOrBuilderList() {
    return configFile_;
  }
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  @java.lang.Override
  public int getConfigFileCount() {
    return configFile_.size();
  }
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto getConfigFile(int index) {
    return configFile_.get(index);
  }
  /**
   * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder getConfigFileOrBuilder(
      int index) {
    return configFile_.get(index);
  }

  public static final int SERIALIZED_OBJECT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> serializedObject_;
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> getSerializedObjectList() {
    return serializedObject_;
  }
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder> 
      getSerializedObjectOrBuilderList() {
    return serializedObject_;
  }
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  @java.lang.Override
  public int getSerializedObjectCount() {
    return serializedObject_.size();
  }
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto getSerializedObject(int index) {
    return serializedObject_.get(index);
  }
  /**
   * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder getSerializedObjectOrBuilder(
      int index) {
    return serializedObject_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProperties(),
        PropertiesDefaultEntryHolder.defaultEntry,
        1);
    for (int i = 0; i < components_.size(); i++) {
      output.writeMessage(2, components_.get(i));
    }
    for (int i = 0; i < configFile_.size(); i++) {
      output.writeMessage(3, configFile_.get(i));
    }
    for (int i = 0; i < serializedObject_.size(); i++) {
      output.writeMessage(4, serializedObject_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      properties__ = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, properties__);
    }
    for (int i = 0; i < components_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, components_.get(i));
    }
    for (int i = 0; i < configFile_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, configFile_.get(i));
    }
    for (int i = 0; i < serializedObject_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, serializedObject_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto)) {
      return super.equals(obj);
    }
    com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto other = (com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto) obj;

    if (!internalGetProperties().equals(
        other.internalGetProperties())) return false;
    if (!getComponentsList()
        .equals(other.getComponentsList())) return false;
    if (!getConfigFileList()
        .equals(other.getConfigFileList())) return false;
    if (!getSerializedObjectList()
        .equals(other.getSerializedObjectList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetProperties().getMap().isEmpty()) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProperties().hashCode();
    }
    if (getComponentsCount() > 0) {
      hash = (37 * hash) + COMPONENTS_FIELD_NUMBER;
      hash = (53 * hash) + getComponentsList().hashCode();
    }
    if (getConfigFileCount() > 0) {
      hash = (37 * hash) + CONFIG_FILE_FIELD_NUMBER;
      hash = (53 * hash) + getConfigFileList().hashCode();
    }
    if (getSerializedObjectCount() > 0) {
      hash = (37 * hash) + SERIALIZED_OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSerializedObjectList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *Root message which contains the full configuration.
   * </pre>
   *
   * Protobuf type {@code olcut.ConfigProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:olcut.ConfigProto)
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.Builder.class);
    }

    // Construct using com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableProperties().clear();
      if (componentsBuilder_ == null) {
        components_ = java.util.Collections.emptyList();
      } else {
        components_ = null;
        componentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (configFileBuilder_ == null) {
        configFile_ = java.util.Collections.emptyList();
      } else {
        configFile_ = null;
        configFileBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (serializedObjectBuilder_ == null) {
        serializedObject_ = java.util.Collections.emptyList();
      } else {
        serializedObject_ = null;
        serializedObjectBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_ConfigProto_descriptor;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto getDefaultInstanceForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto build() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto buildPartial() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto result = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto result) {
      if (componentsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          components_ = java.util.Collections.unmodifiableList(components_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.components_ = components_;
      } else {
        result.components_ = componentsBuilder_.build();
      }
      if (configFileBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          configFile_ = java.util.Collections.unmodifiableList(configFile_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.configFile_ = configFile_;
      } else {
        result.configFile_ = configFileBuilder_.build();
      }
      if (serializedObjectBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          serializedObject_ = java.util.Collections.unmodifiableList(serializedObject_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.serializedObject_ = serializedObject_;
      } else {
        result.serializedObject_ = serializedObjectBuilder_.build();
      }
    }

    private void buildPartial0(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto) {
        return mergeFrom((com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto other) {
      if (other == com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto.getDefaultInstance()) return this;
      internalGetMutableProperties().mergeFrom(
          other.internalGetProperties());
      bitField0_ |= 0x00000001;
      if (componentsBuilder_ == null) {
        if (!other.components_.isEmpty()) {
          if (components_.isEmpty()) {
            components_ = other.components_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureComponentsIsMutable();
            components_.addAll(other.components_);
          }
          onChanged();
        }
      } else {
        if (!other.components_.isEmpty()) {
          if (componentsBuilder_.isEmpty()) {
            componentsBuilder_.dispose();
            componentsBuilder_ = null;
            components_ = other.components_;
            bitField0_ = (bitField0_ & ~0x00000002);
            componentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getComponentsFieldBuilder() : null;
          } else {
            componentsBuilder_.addAllMessages(other.components_);
          }
        }
      }
      if (configFileBuilder_ == null) {
        if (!other.configFile_.isEmpty()) {
          if (configFile_.isEmpty()) {
            configFile_ = other.configFile_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureConfigFileIsMutable();
            configFile_.addAll(other.configFile_);
          }
          onChanged();
        }
      } else {
        if (!other.configFile_.isEmpty()) {
          if (configFileBuilder_.isEmpty()) {
            configFileBuilder_.dispose();
            configFileBuilder_ = null;
            configFile_ = other.configFile_;
            bitField0_ = (bitField0_ & ~0x00000004);
            configFileBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigFileFieldBuilder() : null;
          } else {
            configFileBuilder_.addAllMessages(other.configFile_);
          }
        }
      }
      if (serializedObjectBuilder_ == null) {
        if (!other.serializedObject_.isEmpty()) {
          if (serializedObject_.isEmpty()) {
            serializedObject_ = other.serializedObject_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSerializedObjectIsMutable();
            serializedObject_.addAll(other.serializedObject_);
          }
          onChanged();
        }
      } else {
        if (!other.serializedObject_.isEmpty()) {
          if (serializedObjectBuilder_.isEmpty()) {
            serializedObjectBuilder_.dispose();
            serializedObjectBuilder_ = null;
            serializedObject_ = other.serializedObject_;
            bitField0_ = (bitField0_ & ~0x00000008);
            serializedObjectBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSerializedObjectFieldBuilder() : null;
          } else {
            serializedObjectBuilder_.addAllMessages(other.serializedObject_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties__ = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableProperties().getMutableMap().put(
                  properties__.getKey(), properties__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto m =
                  input.readMessage(
                      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.parser(),
                      extensionRegistry);
              if (componentsBuilder_ == null) {
                ensureComponentsIsMutable();
                components_.add(m);
              } else {
                componentsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto m =
                  input.readMessage(
                      com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.parser(),
                      extensionRegistry);
              if (configFileBuilder_ == null) {
                ensureConfigFileIsMutable();
                configFile_.add(m);
              } else {
                configFileBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto m =
                  input.readMessage(
                      com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.parser(),
                      extensionRegistry);
              if (serializedObjectBuilder_ == null) {
                ensureSerializedObjectIsMutable();
                serializedObject_.add(m);
              } else {
                serializedObjectBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      return properties_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableProperties() {
      if (properties_ == null) {
        properties_ = com.google.protobuf.MapField.newMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!properties_.isMutable()) {
        properties_ = properties_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return properties_;
    }
    public int getPropertiesCount() {
      return internalGetProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    @java.lang.Override
    public boolean containsProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return internalGetProperties().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearProperties() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    public Builder removeProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableProperties() {
      bitField0_ |= 0x00000001;
      return internalGetMutableProperties().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    public Builder putProperties(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableProperties().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 1;</code>
     */
    public Builder putAllProperties(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableProperties().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> components_ =
      java.util.Collections.emptyList();
    private void ensureComponentsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        components_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto>(components_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder> componentsBuilder_;

    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> getComponentsList() {
      if (componentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(components_);
      } else {
        return componentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public int getComponentsCount() {
      if (componentsBuilder_ == null) {
        return components_.size();
      } else {
        return componentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto getComponents(int index) {
      if (componentsBuilder_ == null) {
        return components_.get(index);
      } else {
        return componentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder setComponents(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto value) {
      if (componentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComponentsIsMutable();
        components_.set(index, value);
        onChanged();
      } else {
        componentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder setComponents(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder builderForValue) {
      if (componentsBuilder_ == null) {
        ensureComponentsIsMutable();
        components_.set(index, builderForValue.build());
        onChanged();
      } else {
        componentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder addComponents(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto value) {
      if (componentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComponentsIsMutable();
        components_.add(value);
        onChanged();
      } else {
        componentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder addComponents(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto value) {
      if (componentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureComponentsIsMutable();
        components_.add(index, value);
        onChanged();
      } else {
        componentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder addComponents(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder builderForValue) {
      if (componentsBuilder_ == null) {
        ensureComponentsIsMutable();
        components_.add(builderForValue.build());
        onChanged();
      } else {
        componentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder addComponents(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder builderForValue) {
      if (componentsBuilder_ == null) {
        ensureComponentsIsMutable();
        components_.add(index, builderForValue.build());
        onChanged();
      } else {
        componentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder addAllComponents(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto> values) {
      if (componentsBuilder_ == null) {
        ensureComponentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, components_);
        onChanged();
      } else {
        componentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder clearComponents() {
      if (componentsBuilder_ == null) {
        components_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        componentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public Builder removeComponents(int index) {
      if (componentsBuilder_ == null) {
        ensureComponentsIsMutable();
        components_.remove(index);
        onChanged();
      } else {
        componentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder getComponentsBuilder(
        int index) {
      return getComponentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder getComponentsOrBuilder(
        int index) {
      if (componentsBuilder_ == null) {
        return components_.get(index);  } else {
        return componentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder> 
         getComponentsOrBuilderList() {
      if (componentsBuilder_ != null) {
        return componentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(components_);
      }
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder addComponentsBuilder() {
      return getComponentsFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder addComponentsBuilder(
        int index) {
      return getComponentsFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ComponentProto components = 2;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder> 
         getComponentsBuilderList() {
      return getComponentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder> 
        getComponentsFieldBuilder() {
      if (componentsBuilder_ == null) {
        componentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ComponentProtoOrBuilder>(
                components_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        components_ = null;
      }
      return componentsBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> configFile_ =
      java.util.Collections.emptyList();
    private void ensureConfigFileIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        configFile_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto>(configFile_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder> configFileBuilder_;

    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> getConfigFileList() {
      if (configFileBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configFile_);
      } else {
        return configFileBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public int getConfigFileCount() {
      if (configFileBuilder_ == null) {
        return configFile_.size();
      } else {
        return configFileBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto getConfigFile(int index) {
      if (configFileBuilder_ == null) {
        return configFile_.get(index);
      } else {
        return configFileBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder setConfigFile(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto value) {
      if (configFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigFileIsMutable();
        configFile_.set(index, value);
        onChanged();
      } else {
        configFileBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder setConfigFile(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder builderForValue) {
      if (configFileBuilder_ == null) {
        ensureConfigFileIsMutable();
        configFile_.set(index, builderForValue.build());
        onChanged();
      } else {
        configFileBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder addConfigFile(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto value) {
      if (configFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigFileIsMutable();
        configFile_.add(value);
        onChanged();
      } else {
        configFileBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder addConfigFile(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto value) {
      if (configFileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigFileIsMutable();
        configFile_.add(index, value);
        onChanged();
      } else {
        configFileBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder addConfigFile(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder builderForValue) {
      if (configFileBuilder_ == null) {
        ensureConfigFileIsMutable();
        configFile_.add(builderForValue.build());
        onChanged();
      } else {
        configFileBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder addConfigFile(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder builderForValue) {
      if (configFileBuilder_ == null) {
        ensureConfigFileIsMutable();
        configFile_.add(index, builderForValue.build());
        onChanged();
      } else {
        configFileBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder addAllConfigFile(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto> values) {
      if (configFileBuilder_ == null) {
        ensureConfigFileIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, configFile_);
        onChanged();
      } else {
        configFileBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder clearConfigFile() {
      if (configFileBuilder_ == null) {
        configFile_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        configFileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public Builder removeConfigFile(int index) {
      if (configFileBuilder_ == null) {
        ensureConfigFileIsMutable();
        configFile_.remove(index);
        onChanged();
      } else {
        configFileBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder getConfigFileBuilder(
        int index) {
      return getConfigFileFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder getConfigFileOrBuilder(
        int index) {
      if (configFileBuilder_ == null) {
        return configFile_.get(index);  } else {
        return configFileBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder> 
         getConfigFileOrBuilderList() {
      if (configFileBuilder_ != null) {
        return configFileBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configFile_);
      }
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder addConfigFileBuilder() {
      return getConfigFileFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder addConfigFileBuilder(
        int index) {
      return getConfigFileFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ConfigFileProto config_file = 3;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder> 
         getConfigFileBuilderList() {
      return getConfigFileFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder> 
        getConfigFileFieldBuilder() {
      if (configFileBuilder_ == null) {
        configFileBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigFileProtoOrBuilder>(
                configFile_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        configFile_ = null;
      }
      return configFileBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> serializedObject_ =
      java.util.Collections.emptyList();
    private void ensureSerializedObjectIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        serializedObject_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto>(serializedObject_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder> serializedObjectBuilder_;

    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> getSerializedObjectList() {
      if (serializedObjectBuilder_ == null) {
        return java.util.Collections.unmodifiableList(serializedObject_);
      } else {
        return serializedObjectBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public int getSerializedObjectCount() {
      if (serializedObjectBuilder_ == null) {
        return serializedObject_.size();
      } else {
        return serializedObjectBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto getSerializedObject(int index) {
      if (serializedObjectBuilder_ == null) {
        return serializedObject_.get(index);
      } else {
        return serializedObjectBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder setSerializedObject(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto value) {
      if (serializedObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSerializedObjectIsMutable();
        serializedObject_.set(index, value);
        onChanged();
      } else {
        serializedObjectBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder setSerializedObject(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder builderForValue) {
      if (serializedObjectBuilder_ == null) {
        ensureSerializedObjectIsMutable();
        serializedObject_.set(index, builderForValue.build());
        onChanged();
      } else {
        serializedObjectBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder addSerializedObject(com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto value) {
      if (serializedObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSerializedObjectIsMutable();
        serializedObject_.add(value);
        onChanged();
      } else {
        serializedObjectBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder addSerializedObject(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto value) {
      if (serializedObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSerializedObjectIsMutable();
        serializedObject_.add(index, value);
        onChanged();
      } else {
        serializedObjectBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder addSerializedObject(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder builderForValue) {
      if (serializedObjectBuilder_ == null) {
        ensureSerializedObjectIsMutable();
        serializedObject_.add(builderForValue.build());
        onChanged();
      } else {
        serializedObjectBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder addSerializedObject(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder builderForValue) {
      if (serializedObjectBuilder_ == null) {
        ensureSerializedObjectIsMutable();
        serializedObject_.add(index, builderForValue.build());
        onChanged();
      } else {
        serializedObjectBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder addAllSerializedObject(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto> values) {
      if (serializedObjectBuilder_ == null) {
        ensureSerializedObjectIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serializedObject_);
        onChanged();
      } else {
        serializedObjectBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder clearSerializedObject() {
      if (serializedObjectBuilder_ == null) {
        serializedObject_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        serializedObjectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public Builder removeSerializedObject(int index) {
      if (serializedObjectBuilder_ == null) {
        ensureSerializedObjectIsMutable();
        serializedObject_.remove(index);
        onChanged();
      } else {
        serializedObjectBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder getSerializedObjectBuilder(
        int index) {
      return getSerializedObjectFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder getSerializedObjectOrBuilder(
        int index) {
      if (serializedObjectBuilder_ == null) {
        return serializedObject_.get(index);  } else {
        return serializedObjectBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder> 
         getSerializedObjectOrBuilderList() {
      if (serializedObjectBuilder_ != null) {
        return serializedObjectBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(serializedObject_);
      }
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder addSerializedObjectBuilder() {
      return getSerializedObjectFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder addSerializedObjectBuilder(
        int index) {
      return getSerializedObjectFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.SerializedObjectProto serialized_object = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder> 
         getSerializedObjectBuilderList() {
      return getSerializedObjectFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder> 
        getSerializedObjectFieldBuilder() {
      if (serializedObjectBuilder_ == null) {
        serializedObjectBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SerializedObjectProtoOrBuilder>(
                serializedObject_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        serializedObject_ = null;
      }
      return serializedObjectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:olcut.ConfigProto)
  }

  // @@protoc_insertion_point(class_scope:olcut.ConfigProto)
  private static final com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto();
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigProto>
      PARSER = new com.google.protobuf.AbstractParser<ConfigProto>() {
    @java.lang.Override
    public ConfigProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConfigProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ConfigProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

