// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

// Protobuf Java Version: 3.25.5
package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

public interface MapProvenanceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:olcut.MapProvenanceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>map&lt;string, int32&gt; values = 2;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, int32&gt; values = 2;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getValues();
  /**
   * <code>map&lt;string, int32&gt; values = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getValuesMap();
  /**
   * <code>map&lt;string, int32&gt; values = 2;</code>
   */
  int getValuesOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; values = 2;</code>
   */
  int getValuesOrThrow(
      java.lang.String key);
}
