// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

// Protobuf Java Version: 3.25.5
package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

public interface RootProvenanceProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:olcut.RootProvenanceProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> 
      getOmpList();
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto getOmp(int index);
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  int getOmpCount();
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder> 
      getOmpOrBuilderList();
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder getOmpOrBuilder(
      int index);

  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> 
      getSmpList();
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto getSmp(int index);
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  int getSmpCount();
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder> 
      getSmpOrBuilderList();
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder getSmpOrBuilder(
      int index);

  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> 
      getMmpList();
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto getMmp(int index);
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  int getMmpCount();
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder> 
      getMmpOrBuilderList();
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder getMmpOrBuilder(
      int index);

  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> 
      getLmpList();
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto getLmp(int index);
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  int getLmpCount();
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder> 
      getLmpOrBuilderList();
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder getLmpOrBuilder(
      int index);
}
