// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olcut_proto.proto

package com.oracle.labs.mlrg.olcut.config.protobuf.protos;

/**
 * <pre>
 *Root message for a list of marshalled provenances.
 * </pre>
 *
 * Protobuf type {@code olcut.RootProvenanceProto}
 */
public final class RootProvenanceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:olcut.RootProvenanceProto)
    RootProvenanceProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RootProvenanceProto.newBuilder() to construct.
  private RootProvenanceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RootProvenanceProto() {
    omp_ = java.util.Collections.emptyList();
    smp_ = java.util.Collections.emptyList();
    mmp_ = java.util.Collections.emptyList();
    lmp_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RootProvenanceProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RootProvenanceProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              omp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            omp_.add(
                input.readMessage(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              smp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            smp_.add(
                input.readMessage(com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              mmp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto>();
              mutable_bitField0_ |= 0x00000004;
            }
            mmp_.add(
                input.readMessage(com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              lmp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto>();
              mutable_bitField0_ |= 0x00000008;
            }
            lmp_.add(
                input.readMessage(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        omp_ = java.util.Collections.unmodifiableList(omp_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        smp_ = java.util.Collections.unmodifiableList(smp_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        mmp_ = java.util.Collections.unmodifiableList(mmp_);
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        lmp_ = java.util.Collections.unmodifiableList(lmp_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_RootProvenanceProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_RootProvenanceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder.class);
  }

  public static final int OMP_FIELD_NUMBER = 1;
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> omp_;
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> getOmpList() {
    return omp_;
  }
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder> 
      getOmpOrBuilderList() {
    return omp_;
  }
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  @java.lang.Override
  public int getOmpCount() {
    return omp_.size();
  }
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto getOmp(int index) {
    return omp_.get(index);
  }
  /**
   * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder getOmpOrBuilder(
      int index) {
    return omp_.get(index);
  }

  public static final int SMP_FIELD_NUMBER = 2;
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> smp_;
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> getSmpList() {
    return smp_;
  }
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder> 
      getSmpOrBuilderList() {
    return smp_;
  }
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  @java.lang.Override
  public int getSmpCount() {
    return smp_.size();
  }
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto getSmp(int index) {
    return smp_.get(index);
  }
  /**
   * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder getSmpOrBuilder(
      int index) {
    return smp_.get(index);
  }

  public static final int MMP_FIELD_NUMBER = 3;
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> mmp_;
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> getMmpList() {
    return mmp_;
  }
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder> 
      getMmpOrBuilderList() {
    return mmp_;
  }
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  @java.lang.Override
  public int getMmpCount() {
    return mmp_.size();
  }
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto getMmp(int index) {
    return mmp_.get(index);
  }
  /**
   * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder getMmpOrBuilder(
      int index) {
    return mmp_.get(index);
  }

  public static final int LMP_FIELD_NUMBER = 4;
  private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> lmp_;
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> getLmpList() {
    return lmp_;
  }
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder> 
      getLmpOrBuilderList() {
    return lmp_;
  }
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  @java.lang.Override
  public int getLmpCount() {
    return lmp_.size();
  }
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto getLmp(int index) {
    return lmp_.get(index);
  }
  /**
   * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder getLmpOrBuilder(
      int index) {
    return lmp_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < omp_.size(); i++) {
      output.writeMessage(1, omp_.get(i));
    }
    for (int i = 0; i < smp_.size(); i++) {
      output.writeMessage(2, smp_.get(i));
    }
    for (int i = 0; i < mmp_.size(); i++) {
      output.writeMessage(3, mmp_.get(i));
    }
    for (int i = 0; i < lmp_.size(); i++) {
      output.writeMessage(4, lmp_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < omp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, omp_.get(i));
    }
    for (int i = 0; i < smp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, smp_.get(i));
    }
    for (int i = 0; i < mmp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, mmp_.get(i));
    }
    for (int i = 0; i < lmp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, lmp_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto)) {
      return super.equals(obj);
    }
    com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto other = (com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto) obj;

    if (!getOmpList()
        .equals(other.getOmpList())) return false;
    if (!getSmpList()
        .equals(other.getSmpList())) return false;
    if (!getMmpList()
        .equals(other.getMmpList())) return false;
    if (!getLmpList()
        .equals(other.getLmpList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOmpCount() > 0) {
      hash = (37 * hash) + OMP_FIELD_NUMBER;
      hash = (53 * hash) + getOmpList().hashCode();
    }
    if (getSmpCount() > 0) {
      hash = (37 * hash) + SMP_FIELD_NUMBER;
      hash = (53 * hash) + getSmpList().hashCode();
    }
    if (getMmpCount() > 0) {
      hash = (37 * hash) + MMP_FIELD_NUMBER;
      hash = (53 * hash) + getMmpList().hashCode();
    }
    if (getLmpCount() > 0) {
      hash = (37 * hash) + LMP_FIELD_NUMBER;
      hash = (53 * hash) + getLmpList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Root message for a list of marshalled provenances.
   * </pre>
   *
   * Protobuf type {@code olcut.RootProvenanceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:olcut.RootProvenanceProto)
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_RootProvenanceProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_RootProvenanceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.class, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder.class);
    }

    // Construct using com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOmpFieldBuilder();
        getSmpFieldBuilder();
        getMmpFieldBuilder();
        getLmpFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ompBuilder_ == null) {
        omp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ompBuilder_.clear();
      }
      if (smpBuilder_ == null) {
        smp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        smpBuilder_.clear();
      }
      if (mmpBuilder_ == null) {
        mmp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        mmpBuilder_.clear();
      }
      if (lmpBuilder_ == null) {
        lmp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        lmpBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.OlcutProto.internal_static_olcut_RootProvenanceProto_descriptor;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getDefaultInstanceForType() {
      return com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto build() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto buildPartial() {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto result = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto(this);
      int from_bitField0_ = bitField0_;
      if (ompBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          omp_ = java.util.Collections.unmodifiableList(omp_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.omp_ = omp_;
      } else {
        result.omp_ = ompBuilder_.build();
      }
      if (smpBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          smp_ = java.util.Collections.unmodifiableList(smp_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.smp_ = smp_;
      } else {
        result.smp_ = smpBuilder_.build();
      }
      if (mmpBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          mmp_ = java.util.Collections.unmodifiableList(mmp_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.mmp_ = mmp_;
      } else {
        result.mmp_ = mmpBuilder_.build();
      }
      if (lmpBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          lmp_ = java.util.Collections.unmodifiableList(lmp_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lmp_ = lmp_;
      } else {
        result.lmp_ = lmpBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto) {
        return mergeFrom((com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto other) {
      if (other == com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.getDefaultInstance()) return this;
      if (ompBuilder_ == null) {
        if (!other.omp_.isEmpty()) {
          if (omp_.isEmpty()) {
            omp_ = other.omp_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOmpIsMutable();
            omp_.addAll(other.omp_);
          }
          onChanged();
        }
      } else {
        if (!other.omp_.isEmpty()) {
          if (ompBuilder_.isEmpty()) {
            ompBuilder_.dispose();
            ompBuilder_ = null;
            omp_ = other.omp_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ompBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOmpFieldBuilder() : null;
          } else {
            ompBuilder_.addAllMessages(other.omp_);
          }
        }
      }
      if (smpBuilder_ == null) {
        if (!other.smp_.isEmpty()) {
          if (smp_.isEmpty()) {
            smp_ = other.smp_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSmpIsMutable();
            smp_.addAll(other.smp_);
          }
          onChanged();
        }
      } else {
        if (!other.smp_.isEmpty()) {
          if (smpBuilder_.isEmpty()) {
            smpBuilder_.dispose();
            smpBuilder_ = null;
            smp_ = other.smp_;
            bitField0_ = (bitField0_ & ~0x00000002);
            smpBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSmpFieldBuilder() : null;
          } else {
            smpBuilder_.addAllMessages(other.smp_);
          }
        }
      }
      if (mmpBuilder_ == null) {
        if (!other.mmp_.isEmpty()) {
          if (mmp_.isEmpty()) {
            mmp_ = other.mmp_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMmpIsMutable();
            mmp_.addAll(other.mmp_);
          }
          onChanged();
        }
      } else {
        if (!other.mmp_.isEmpty()) {
          if (mmpBuilder_.isEmpty()) {
            mmpBuilder_.dispose();
            mmpBuilder_ = null;
            mmp_ = other.mmp_;
            bitField0_ = (bitField0_ & ~0x00000004);
            mmpBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMmpFieldBuilder() : null;
          } else {
            mmpBuilder_.addAllMessages(other.mmp_);
          }
        }
      }
      if (lmpBuilder_ == null) {
        if (!other.lmp_.isEmpty()) {
          if (lmp_.isEmpty()) {
            lmp_ = other.lmp_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLmpIsMutable();
            lmp_.addAll(other.lmp_);
          }
          onChanged();
        }
      } else {
        if (!other.lmp_.isEmpty()) {
          if (lmpBuilder_.isEmpty()) {
            lmpBuilder_.dispose();
            lmpBuilder_ = null;
            lmp_ = other.lmp_;
            bitField0_ = (bitField0_ & ~0x00000008);
            lmpBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLmpFieldBuilder() : null;
          } else {
            lmpBuilder_.addAllMessages(other.lmp_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> omp_ =
      java.util.Collections.emptyList();
    private void ensureOmpIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        omp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto>(omp_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder> ompBuilder_;

    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> getOmpList() {
      if (ompBuilder_ == null) {
        return java.util.Collections.unmodifiableList(omp_);
      } else {
        return ompBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public int getOmpCount() {
      if (ompBuilder_ == null) {
        return omp_.size();
      } else {
        return ompBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto getOmp(int index) {
      if (ompBuilder_ == null) {
        return omp_.get(index);
      } else {
        return ompBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder setOmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto value) {
      if (ompBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOmpIsMutable();
        omp_.set(index, value);
        onChanged();
      } else {
        ompBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder setOmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder builderForValue) {
      if (ompBuilder_ == null) {
        ensureOmpIsMutable();
        omp_.set(index, builderForValue.build());
        onChanged();
      } else {
        ompBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder addOmp(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto value) {
      if (ompBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOmpIsMutable();
        omp_.add(value);
        onChanged();
      } else {
        ompBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder addOmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto value) {
      if (ompBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOmpIsMutable();
        omp_.add(index, value);
        onChanged();
      } else {
        ompBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder addOmp(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder builderForValue) {
      if (ompBuilder_ == null) {
        ensureOmpIsMutable();
        omp_.add(builderForValue.build());
        onChanged();
      } else {
        ompBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder addOmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder builderForValue) {
      if (ompBuilder_ == null) {
        ensureOmpIsMutable();
        omp_.add(index, builderForValue.build());
        onChanged();
      } else {
        ompBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder addAllOmp(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto> values) {
      if (ompBuilder_ == null) {
        ensureOmpIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, omp_);
        onChanged();
      } else {
        ompBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder clearOmp() {
      if (ompBuilder_ == null) {
        omp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ompBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public Builder removeOmp(int index) {
      if (ompBuilder_ == null) {
        ensureOmpIsMutable();
        omp_.remove(index);
        onChanged();
      } else {
        ompBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder getOmpBuilder(
        int index) {
      return getOmpFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder getOmpOrBuilder(
        int index) {
      if (ompBuilder_ == null) {
        return omp_.get(index);  } else {
        return ompBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder> 
         getOmpOrBuilderList() {
      if (ompBuilder_ != null) {
        return ompBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(omp_);
      }
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder addOmpBuilder() {
      return getOmpFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder addOmpBuilder(
        int index) {
      return getOmpFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ObjectProvenanceProto omp = 1;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder> 
         getOmpBuilderList() {
      return getOmpFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder> 
        getOmpFieldBuilder() {
      if (ompBuilder_ == null) {
        ompBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ObjectProvenanceProtoOrBuilder>(
                omp_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        omp_ = null;
      }
      return ompBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> smp_ =
      java.util.Collections.emptyList();
    private void ensureSmpIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        smp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto>(smp_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder> smpBuilder_;

    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> getSmpList() {
      if (smpBuilder_ == null) {
        return java.util.Collections.unmodifiableList(smp_);
      } else {
        return smpBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public int getSmpCount() {
      if (smpBuilder_ == null) {
        return smp_.size();
      } else {
        return smpBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto getSmp(int index) {
      if (smpBuilder_ == null) {
        return smp_.get(index);
      } else {
        return smpBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder setSmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto value) {
      if (smpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSmpIsMutable();
        smp_.set(index, value);
        onChanged();
      } else {
        smpBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder setSmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder builderForValue) {
      if (smpBuilder_ == null) {
        ensureSmpIsMutable();
        smp_.set(index, builderForValue.build());
        onChanged();
      } else {
        smpBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder addSmp(com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto value) {
      if (smpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSmpIsMutable();
        smp_.add(value);
        onChanged();
      } else {
        smpBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder addSmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto value) {
      if (smpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSmpIsMutable();
        smp_.add(index, value);
        onChanged();
      } else {
        smpBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder addSmp(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder builderForValue) {
      if (smpBuilder_ == null) {
        ensureSmpIsMutable();
        smp_.add(builderForValue.build());
        onChanged();
      } else {
        smpBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder addSmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder builderForValue) {
      if (smpBuilder_ == null) {
        ensureSmpIsMutable();
        smp_.add(index, builderForValue.build());
        onChanged();
      } else {
        smpBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder addAllSmp(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto> values) {
      if (smpBuilder_ == null) {
        ensureSmpIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, smp_);
        onChanged();
      } else {
        smpBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder clearSmp() {
      if (smpBuilder_ == null) {
        smp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        smpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public Builder removeSmp(int index) {
      if (smpBuilder_ == null) {
        ensureSmpIsMutable();
        smp_.remove(index);
        onChanged();
      } else {
        smpBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder getSmpBuilder(
        int index) {
      return getSmpFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder getSmpOrBuilder(
        int index) {
      if (smpBuilder_ == null) {
        return smp_.get(index);  } else {
        return smpBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder> 
         getSmpOrBuilderList() {
      if (smpBuilder_ != null) {
        return smpBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(smp_);
      }
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder addSmpBuilder() {
      return getSmpFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder addSmpBuilder(
        int index) {
      return getSmpFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.SimpleProvenanceProto smp = 2;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder> 
         getSmpBuilderList() {
      return getSmpFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder> 
        getSmpFieldBuilder() {
      if (smpBuilder_ == null) {
        smpBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.SimpleProvenanceProtoOrBuilder>(
                smp_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        smp_ = null;
      }
      return smpBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> mmp_ =
      java.util.Collections.emptyList();
    private void ensureMmpIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        mmp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto>(mmp_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder> mmpBuilder_;

    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> getMmpList() {
      if (mmpBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mmp_);
      } else {
        return mmpBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public int getMmpCount() {
      if (mmpBuilder_ == null) {
        return mmp_.size();
      } else {
        return mmpBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto getMmp(int index) {
      if (mmpBuilder_ == null) {
        return mmp_.get(index);
      } else {
        return mmpBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder setMmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto value) {
      if (mmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMmpIsMutable();
        mmp_.set(index, value);
        onChanged();
      } else {
        mmpBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder setMmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder builderForValue) {
      if (mmpBuilder_ == null) {
        ensureMmpIsMutable();
        mmp_.set(index, builderForValue.build());
        onChanged();
      } else {
        mmpBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder addMmp(com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto value) {
      if (mmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMmpIsMutable();
        mmp_.add(value);
        onChanged();
      } else {
        mmpBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder addMmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto value) {
      if (mmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMmpIsMutable();
        mmp_.add(index, value);
        onChanged();
      } else {
        mmpBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder addMmp(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder builderForValue) {
      if (mmpBuilder_ == null) {
        ensureMmpIsMutable();
        mmp_.add(builderForValue.build());
        onChanged();
      } else {
        mmpBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder addMmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder builderForValue) {
      if (mmpBuilder_ == null) {
        ensureMmpIsMutable();
        mmp_.add(index, builderForValue.build());
        onChanged();
      } else {
        mmpBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder addAllMmp(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto> values) {
      if (mmpBuilder_ == null) {
        ensureMmpIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mmp_);
        onChanged();
      } else {
        mmpBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder clearMmp() {
      if (mmpBuilder_ == null) {
        mmp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        mmpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public Builder removeMmp(int index) {
      if (mmpBuilder_ == null) {
        ensureMmpIsMutable();
        mmp_.remove(index);
        onChanged();
      } else {
        mmpBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder getMmpBuilder(
        int index) {
      return getMmpFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder getMmpOrBuilder(
        int index) {
      if (mmpBuilder_ == null) {
        return mmp_.get(index);  } else {
        return mmpBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder> 
         getMmpOrBuilderList() {
      if (mmpBuilder_ != null) {
        return mmpBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mmp_);
      }
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder addMmpBuilder() {
      return getMmpFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder addMmpBuilder(
        int index) {
      return getMmpFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.MapProvenanceProto mmp = 3;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder> 
         getMmpBuilderList() {
      return getMmpFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder> 
        getMmpFieldBuilder() {
      if (mmpBuilder_ == null) {
        mmpBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.MapProvenanceProtoOrBuilder>(
                mmp_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        mmp_ = null;
      }
      return mmpBuilder_;
    }

    private java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> lmp_ =
      java.util.Collections.emptyList();
    private void ensureLmpIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        lmp_ = new java.util.ArrayList<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto>(lmp_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder> lmpBuilder_;

    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> getLmpList() {
      if (lmpBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lmp_);
      } else {
        return lmpBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public int getLmpCount() {
      if (lmpBuilder_ == null) {
        return lmp_.size();
      } else {
        return lmpBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto getLmp(int index) {
      if (lmpBuilder_ == null) {
        return lmp_.get(index);
      } else {
        return lmpBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder setLmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto value) {
      if (lmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLmpIsMutable();
        lmp_.set(index, value);
        onChanged();
      } else {
        lmpBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder setLmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder builderForValue) {
      if (lmpBuilder_ == null) {
        ensureLmpIsMutable();
        lmp_.set(index, builderForValue.build());
        onChanged();
      } else {
        lmpBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder addLmp(com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto value) {
      if (lmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLmpIsMutable();
        lmp_.add(value);
        onChanged();
      } else {
        lmpBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder addLmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto value) {
      if (lmpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLmpIsMutable();
        lmp_.add(index, value);
        onChanged();
      } else {
        lmpBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder addLmp(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder builderForValue) {
      if (lmpBuilder_ == null) {
        ensureLmpIsMutable();
        lmp_.add(builderForValue.build());
        onChanged();
      } else {
        lmpBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder addLmp(
        int index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder builderForValue) {
      if (lmpBuilder_ == null) {
        ensureLmpIsMutable();
        lmp_.add(index, builderForValue.build());
        onChanged();
      } else {
        lmpBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder addAllLmp(
        java.lang.Iterable<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto> values) {
      if (lmpBuilder_ == null) {
        ensureLmpIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lmp_);
        onChanged();
      } else {
        lmpBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder clearLmp() {
      if (lmpBuilder_ == null) {
        lmp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        lmpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public Builder removeLmp(int index) {
      if (lmpBuilder_ == null) {
        ensureLmpIsMutable();
        lmp_.remove(index);
        onChanged();
      } else {
        lmpBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder getLmpBuilder(
        int index) {
      return getLmpFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder getLmpOrBuilder(
        int index) {
      if (lmpBuilder_ == null) {
        return lmp_.get(index);  } else {
        return lmpBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder> 
         getLmpOrBuilderList() {
      if (lmpBuilder_ != null) {
        return lmpBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lmp_);
      }
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder addLmpBuilder() {
      return getLmpFieldBuilder().addBuilder(
          com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder addLmpBuilder(
        int index) {
      return getLmpFieldBuilder().addBuilder(
          index, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .olcut.ListProvenanceProto lmp = 4;</code>
     */
    public java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder> 
         getLmpBuilderList() {
      return getLmpFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder> 
        getLmpFieldBuilder() {
      if (lmpBuilder_ == null) {
        lmpBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.ListProvenanceProtoOrBuilder>(
                lmp_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        lmp_ = null;
      }
      return lmpBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:olcut.RootProvenanceProto)
  }

  // @@protoc_insertion_point(class_scope:olcut.RootProvenanceProto)
  private static final com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto();
  }

  public static com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RootProvenanceProto>
      PARSER = new com.google.protobuf.AbstractParser<RootProvenanceProto>() {
    @java.lang.Override
    public RootProvenanceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RootProvenanceProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RootProvenanceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RootProvenanceProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

